### ISSUE TITLE
name 'Antiviruskiller' is not defined

### ISSUE THREAD

**Issue by nuniseis7** [nopeqk/Telegram-RAT#1]
When trying to debug the code this error appears. Any ideas?
![Captura de pantalla (226)](https://user-images.githubusercontent.com/65106055/92196008-e3c06100-ee33-11ea-85ce-7e8ced49dbb5.png)

**Comment by nopeqk** [comment]
Should be fixed by now I guess. Just pushed. If not reply.

**Comment by nuniseis7** [comment]
It's working correctly. I love it.

**Comment by nopeqk** [comment]
thank you man! I like to hear that from you 👍
